//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MortgageCalculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mortgage1
    {
        public int Id { get; set; }
        public string Principle { get; set; }
        public string Rate { get; set; }
        public string Years { get; set; }
        public string MonthlyPayment { get; set; }
    }
}
